.
.TH "MURMUR" "1" "May 2025" "" ""
.
.SH "NAME"
\fBmurmur\fR \-\- Command line MurmurHash3 Utility
.
.SH "SYNOPSIS"
\fBmurmur\fR [\-hV] [options]
.
.SH "OPTIONS"
  \-V, \-\-version
      output program version
.
.P
  \-h, \-\-help
      output help information
.
.P
  \-\-seed=[seed]
      hash seed (optional)
.
.SH "EXAMPLES"
  \fB
  $ echo \-n kinkajou | murmur
  3067714808
  \fR
.
.P
  \fB
  $ echo \-n panda | murmur \-\-seed=10
  1406483717
  \fR
.
.SH "AUTHOR"
.
.IP "\(bu" 4
Joseph Werle \fIjoseph\.werle@gmail\.com\fR
.
.IP "" 0
.
.SH "REPORTING BUGS"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/murmurhash\.c/issues\fR
.
.IP "" 0
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
\fIhttps://github\.com/jwerle/murmurhash\.c\fR
.
.IP "" 0
.
.SH "LICENSE"
MIT
